name: Actions Demo
run-name: Demo 🚀
on: push
jobs:
  test-make-func:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
     - name: Print Hello from Hexlet
       uses: hexlet-components/hello-from-hexlet-action@release
     - run: make install
     - run: make test
     - run: make lint
